const backendDomin ="http://localhost:8080"
// const backendDomin ="https://e-commerce-web-aq5g.onrender.com"

const summmryApi={
    signUp:{
        url:`${backendDomin}/api/signup`,
        method:"post"
    },
    signIn:{
        url:`${backendDomin}/api/signin`,
        method:"post"
    },
    current_user:{
        url:`${backendDomin}/api/user`,
        method:"get"
    },
    logout_user:{
        url:`${backendDomin}/api/userLogout`,
        method:"get"
    },
    allUser:{
        url:`${backendDomin}/api/all-user`,
        method:"get"
    },
    updateUser:{
        url:`${backendDomin}/api/updateUser`,
        method:"put"
    },
    uploadProduct:{
        url:`${backendDomin}/api/uploadProduct`,
        method:"post"
    },
    getProducts:{
        url:`${backendDomin}/api/getProducts`,
        method:"get"
    },
    updateProducts:{
        url:`${backendDomin}/api/updateProducts`,
        method:"put"
    },
    deleteProduct:{
        url:`${backendDomin}/api/deleteProduct`,
        method:"delete"
    },
    productCategory:{
        url:`${backendDomin}/api/productCategory`,
        method:"get"
    },
    productCategoryWise:{
        url:`${backendDomin}/api/productCategoryWise`,
        method:"post"
    },
    productDetailes:{
        url:`${backendDomin}/api/productDetailes`,
        method:"post"
    },
    addToCart:{
        url:`${backendDomin}/api/addToCart`,
        method:"post"
    },
    countProductCart:{
        url:`${backendDomin}/api/countProductCart`,
        method:"get"
    },
    cartView:{
        url:`${backendDomin}/api/cartView`,
        method:"get"
    },
    updateCart:{
        url:`${backendDomin}/api/updateCart`,
        method:"post"
    },
    deleteCartProduct:{
        url:`${backendDomin}/api/deleteCartProduct`,
        method:"delete"
    },
    search:{
        url:`${backendDomin}/api/search`,
        method:"get"
    },
}
 export default summmryApi
 